### ISSUE TITLE
Update faker.js

### ISSUE THREAD

**Issue by JeromeDeLeon** [haterapps/fake-data#18]
I just upgraded to PRO version but it seemed like faker is missing some new stuff like `datatype`.

Is it possible to have this updated to the latest version?

**Comment by haterapps** [comment]
Hello,

Unfortunately, Fake Data does not contain the latest version of faker.js, as you already noticed. 
I will look into this and hope to bundle the latest library version in the next update. However, this will take a little while, as I need to finish migration to MV3, as described in #12. I can see that there have been some major updates for faker-js since the author changed.

Sorry for this inconvenience.

**Comment by JeromeDeLeon** [comment]
No worries. I'm happy to wait or just create the utility myself for the meantime. Thank you so much

**Comment by haterapps** [comment]
Hello,

Sorry for the big delay on this. The latest version of Fake Data (4.0.0) now contains the updated Faker.js library (forked at 7.2.0)

The new version of the extension is already available for Chrome, following Firefox and Edge in the next days.
