### ISSUE TITLE
Enhance `fakeData` API docs

### ISSUE THREAD

**Issue by JeromeDeLeon** [haterapps/fake-data#20]
Hello, I really do like this library that I decided to try PRO version. Thank you for this.

Correct me if I'm wrong but I couldn't find any docs that say about `fakeData.getFakeValue` or not sure if it should be used publicly but it's so useful to have it here for other users as well like so

```js
return new Promise(async (resolve) => {
  const previousData = await fakeData.getLastGeneratedValue('email');
  return resolve(previousData || fakeData.getFakeValue('email'));
});
```

**Comment by haterapps** [comment]
Hello.

I agree that the current documentation is lame and out of date. I am actually in the process of writing a new documentation, which will be hosted [here](https://docs.fakedata.pro/). This one will be more complete and will look more pretty than the current one. 

I intend to cover pretty much everything that Fake Data can do, including the functions that you mentioned. Right now it's only 10% done, but in the coming weeks will be finished.


Thank you for your support!

**Comment by haterapps** [comment]
Hello,

The new documentation page for `fakeData.*` methods can be accessed from the following link:
https://docs.fakedata.pro/writing-code/fake-data-api.html

While the documentation website is still a work in progress, I will mark this issue as resolved since it was related only to `fakeData` API docs. Feel free to reopen it if there is any issue that you identify.

Thanks!

**Comment by JeromeDeLeon** [comment]
I've checked all changes from my requests and they looked fine, especially the docs! Thank you so much for putting effort to this!
