### ISSUE TITLE
Handle react-select library

### ISSUE THREAD

**Issue by naustra** [haterapps/fake-data#21]
Hello ! 

Is there a way to fill randomly a multi-select like this one with fake-data ?
https://codesandbox.io/s/formik-react-select-multi-typescript-qsrj2?file=/src/CustomSelect.tsx

**Comment by haterapps** [comment]
Hello,

At this moment Fake Data can't fill dropdowns created by react-select library.

Since this is a pretty popular library, I will keep this task open and implement the support for it in a future update.

In the meantime, if you don't want to wait and are pretty comfortable with writing js code, you can register custom elements in Fake Data and write code to handle them. Here is a tutorial for that:
https://docs.fakedata.pro/writing-code/register-custom-elements.html

**Comment by haterapps** [comment]
Hello,

Fake Data 4.0.0 can now fill react-select dropdowns. This custom integration needs to be enabled in the settings page. Please see this quick tutorial:

https://docs.fakedata.pro/how-to-use-fake-data/settings/developer-options/custom-integrations/react-select.html

Normally, this is a paid feature, like the rest of the integrations with third-party UI libraries, but feel free to send me an email at frustrations@haterapps.com if you don't have one and we'll see from there.


Version 4.0.0 of Fake Data is already available in Chrome, following with Firefox and Edge in the next days.
